/*
 * This source file was generated by the Gradle 'init' task
 */
package org.APCSLowell;

import java.lang.Math;

public class GoogleBillboard {
    public boolean isPrime(long n) {
        for (int i = 2; i <= Math.sqrt(n); i++) {
            if (n % i == 0) return false;
        }
        return true;
    }
    public long firstPrimeNumberIn(String n) {
        for (int i = 0; i < n.length() - 10; i++) {
            long x = Long.valueOf(n.substring(i, i + 10));
            if (isPrime(x)) return x;
        }
        return -1;
    }
}
